build.gradle
=> junit version revert

charts/sscs-ccd-case-migration/Chart.yaml
=> Fix deployment

build.gradle, charts/sscs-ccd-case-migration/Chart.yaml, charts/sscs-ccd-case-migration/values.yaml, src/main/java/uk/gov/hmcts/reform/migration/CaseMigrationRunner.java, src/main/java/uk/gov/hmcts/reform/migration/query/CaseManagementLocactionQuery.java, src/main/java/uk/gov/hmcts/reform/migration/query/DwpElasticSearchQuery.java, src/main/java/uk/gov/hmcts/reform/migration/service/CaseManagementLocationMigrationImpl.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/migration/query/CaseManagementLocationQueryTest.java, src/test/java/uk/gov/hmcts/reform/migration/query/DwpElasticSearchQueryTest.java, src/test/java/uk/gov/hmcts/reform/migration/service/CaseManagementLocationMigrationImplTest.java
https://tools.hmcts.net/jira/browse/SSCS-12481
caseManagementLocation migration implementation
```
[ ] Yes
[ ] No
```
=> caseManagementLocation migration implementation

src/test/java/uk/gov/hmcts/reform/migration/service/CaseManagementLocationMigrationImplTest.java
code coverage
```
[ ] Yes
[ ] No
```
=> code coverage

.github/renovate.json
https://tools.hmcts.net/jira/browse/SSCSCI-1388
extend renovate config
=> SSCSCI-1388 - Add renovate config

src/main/java/uk/gov/hmcts/reform/migration/service/CaseOutcomeMigrationServiceImpl.java
https://tools.hmcts.net/jira/browse/SSCSCI-1340
Change event summary and comment to approved text
=> SSCSCI-1340 - update case outcome migration event text info

README.md
https://tools.hmcts.net/jira/browse/SSCSCI-1462
test if build is green with renovate config changes
=> SSCSCI-1462 - test renovate config

src/main/java/uk/gov/hmcts/reform/migration/service/HmctsDwpStateMigrationImpl.java, src/test/java/uk/gov/hmcts/reform/migration/service/HmctsDwpStateMigrationImplTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-1485
remove void/dormant check from migration
```
[ ] Yes
[x] No
```
=> SSCSCI-1485 - Clear hmctsDwpState for Non Dormant and Non Void cases

src/main/java/uk/gov/hmcts/reform/migration/service/HmctsDwpStateMigrationImpl.java, src/test/java/uk/gov/hmcts/reform/migration/service/HmctsDwpStateMigrationImplTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-1484
Add void / dormant check for case migration
```
[ ] Yes
[x] No
```
=> SSCSCI-1484 - add void/dormant check

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/migration/service/CaseManagementLocationMigrationImpl.java, src/test/java/uk/gov/hmcts/reform/migration/service/CaseManagementLocationMigrationImplTest.java
=> SSCSCI RegionalProcessingCenter

src/main/java/uk/gov/hmcts/reform/migration/repository/CaseLoader.java
https://tools.hmcts.net/jira/browse/SSCSCI-1551
```
[ ] Yes
[x] No
```
=> SSCSCI-1551 - enable migration

src/main/java/uk/gov/hmcts/reform/migration/repository/CaseLoader.java
https://tools.hmcts.net/jira/browse/SSCSCI-1550
```
[ ] Yes
[x] No
```
=> SSCSCI-1550 - enable migration

src/main/java/uk/gov/hmcts/reform/migration/ccd/HttpMessageConverterConfiguration.java, src/main/java/uk/gov/hmcts/reform/migration/service/CaseManagementLocationMigrationImpl.java, src/main/java/uk/gov/hmcts/reform/migration/service/CaseOutcomeGapsMigrationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/migration/service/CaseOutcomeMigration.java, src/main/java/uk/gov/hmcts/reform/migration/service/CompletedHearingsOutcomesMigration.java, src/main/java/uk/gov/hmcts/reform/migration/service/HmctsDwpStateMigrationImpl.java, src/main/java/uk/gov/hmcts/reform/migration/service/NonListedHearingsOutcomesMigration.java, src/test/java/uk/gov/hmcts/reform/migration/service/CaseManagementLocationMigrationImplTest.java, src/test/java/uk/gov/hmcts/reform/migration/service/CompletedHearingsOutcomesMigrationTest.java, src/test/java/uk/gov/hmcts/reform/migration/service/HmctsDwpStateMigrationImplTest.java, src/test/java/uk/gov/hmcts/reform/migration/service/NonListedHearingsOutcomesMigrationTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-1551
Remove autowired json mapper
```
[ ] Yes
[x] No
```
=> SSCSCI-1551 - revert json mapper changes

src/main/java/uk/gov/hmcts/reform/migration/service/NonListedHearingsOutcomesMigration.java, src/test/java/uk/gov/hmcts/reform/migration/service/NonListedHearingsOutcomesMigrationTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-1551
Alter excluded hmc statuses from Listed to awaiting_listing after discussion with POs on 06/03/25
Altered event description after discussion with POs on 06/03/25
```
[ ] Yes
[x] No
```
=> SSCSCI-1551 - update excluded statuses

charts/sscs-ccd-case-migration/Chart.yaml, charts/sscs-ccd-case-migration/values.yaml, src/main/java/uk/gov/hmcts/reform/migration/MigrationDataEncoderApp.java, src/main/java/uk/gov/hmcts/reform/migration/repository/CaseLoader.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/CaseOutcomeMigration.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/HmctsDwpStateMigrationImpl.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/MultipleHearingsOutcomeMigration.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/NonListedHearingsOutcomesMigration.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/WaFieldsRemovalServiceImpl.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/migration/repository/CaseLoaderTest.java, src/test/java/uk/gov/hmcts/reform/migration/service/migrate/MultipleHearingsOutcomeMigrationTest.java, src/test/java/uk/gov/hmcts/reform/migration/service/migrate/NonListedHearingsOutcomesMigrationTest.java, testMigrationSourceFile.csv
https://tools.hmcts.net/jira/browse/SSCSCI-1765
Add migration mapping for a case outcome to a hearing outcome for a specified hearing ID
```
[ ] Yes
[x] No
```
=> SSCSCI-1765 - multiple hearing migrations

src/main/java/uk/gov/hmcts/reform/migration/service/migrate/MultipleHearingsOutcomeMigration.java
See [SSCSCI-1839](https://tools.hmcts.net/jira/browse/SSCSCI-1839)
added null check to setHearingOutcome
Migrated a case without a hearing outcome and another with an existing one in AAT, both were successful.
Cases used: 1736182844784483 and 1734357695414404
```
[ ] Yes
[x] No
```
=> SSCSCI-1839 multiple hearing cases with existing hearing outcome fix

src/main/java/uk/gov/hmcts/reform/migration/service/migrate/DefaultPanelCompositionMigration.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/UpdateListingReqsMissingAmendReasonMigration.java, src/test/java/uk/gov/hmcts/reform/migration/service/migrate/DefaultPanelCompositionMigrationTest.java, src/test/java/uk/gov/hmcts/reform/migration/service/migrate/UpdateListingReqsMissingAmendReasonMigrationTest.java
- https://tools.hmcts.net/jira/browse/SSCSCI-1846
- set override duration to prevent UpdateListingRequirements event failure
```
[ ] Yes
[X] No
```
=> SSCSCI-1729: set override duration if null

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-1846
```
[ ] Yes
[ ] No
```
=> SSCSCI-1846: adding java time module

build.gradle
=> SSCSCI-1846: adding jdk8 module

build.gradle, src/main/resources/application.properties
=> SSCSCI-1846: adding jackson modules and config

src/main/java/uk/gov/hmcts/reform/migration/service/migrate/DefaultPanelCompositionMigration.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/UpdateListingReqsMissingAmendReasonMigration.java, src/test/java/uk/gov/hmcts/reform/migration/service/migrate/DefaultPanelCompositionMigrationTest.java, src/test/java/uk/gov/hmcts/reform/migration/service/migrate/UpdateListingReqsMissingAmendReasonMigrationTest.java
=> SSCSCI-1846: remove caseData conversion to prevent deserialisation issue

build.gradle
See [SSCSCI-1862](https://tools.hmcts.net/jira/browse/SSCSCI-1862)
sscs-common bump to 6.2.8
```
[ ] Yes
[x] No
```
=> SSCSCI-1862: sscs-common bump

charts/sscs-ccd-case-migration/Chart.yaml, charts/sscs-ccd-case-migration/values.yaml, src/main/java/uk/gov/hmcts/reform/migration/repository/EncodedStringCaseList.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/CaseOutcomeMigration.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/DefaultPanelCompositionMigration.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/HmctsDwpStateMigrationImpl.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/MultipleHearingsOutcomeMigration.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/UpdateListingReqsMissingAmendReasonMigration.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/WaFieldsRemovalServiceImpl.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/migration/repository/EncodedStringCaseListTest.java, src/test/java/uk/gov/hmcts/reform/migration/service/migrate/DefaultPanelCompositionMigrationTest.java, src/test/java/uk/gov/hmcts/reform/migration/service/migrate/UpdateListingReqsMissingAmendReasonMigrationTest.java
- SSCSCI-1846
- verify case state before running migration
```
[ ] Yes
[x] No
```
=> SSCSCI-1846: verify case state before running migration

src/main/java/uk/gov/hmcts/reform/migration/query/OldDraftsSearchQuery.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/OldDraftAppealsArchiveService.java, src/test/java/uk/gov/hmcts/reform/migration/service/migrate/OldDraftAppealsArchiveServiceTest.java
See [SSCSCI-1868](https://tools.hmcts.net/jira/browse/SSCSCI-1868)
Reseting archive draft migration changes 
```
[ ] Yes
[ ] No
```
=> SSCSCI-1930: reset draft migration after test

src/main/java/uk/gov/hmcts/reform/migration/service/migrate/DefaultPanelCompositionMigration.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/UpdateListingReqsMissingAmendReasonMigration.java, src/test/java/uk/gov/hmcts/reform/migration/service/migrate/DefaultPanelCompositionMigrationTest.java, src/test/java/uk/gov/hmcts/reform/migration/service/migrate/UpdateListingReqsMissingAmendReasonMigrationTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-1953 / https://tools.hmcts.net/jira/browse/SSCSCI-1729
Setting amend reason in default panel composition migration
Only migrate if hmc status is Awaiting Listing, Update Requested or Update Submitted
```
[ ] Yes
[x] No
```
=> SSCSCI-1953 - set AmendReasons

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-1877
update commons
```
[ ] Yes
[x] No
```
=> SSCSCI-1877 - update commons

build.gradle
- https://tools.hmcts.net/jira/browse/SSCSCI-1978
- upgrade sscs-common to v6.3.8
```
[ ] Yes
[x] No
```
=> upgrade sscs-common to v6.3.8

src/main/java/uk/gov/hmcts/reform/migration/query/DefaultPanelCompositionQuery.java, src/main/java/uk/gov/hmcts/reform/migration/service/migrate/DefaultPanelCompositionMigration.java, src/test/java/uk/gov/hmcts/reform/migration/service/migrate/DefaultPanelCompositionMigrationTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-1729
Throw an error in DefaultPanelCompositionMigration if hearing route is not list assist, or panelMemberComposition is not null. 
```
[ ] Yes
[X] No
```
=> SSCSCI-1729: HearingRoute and PMC check

src/main/java/uk/gov/hmcts/reform/migration/query/DefaultPanelCompositionQuery.java
Change sort order to descending 
```
[ ] Yes
[ ] No
```
=> Update DefaultPanelCompositionQuery sort order

src/main/java/uk/gov/hmcts/reform/migration/service/migrate/DefaultPanelCompositionMigration.java
Add logging during fetchCasesToMigrate in 
```
[ ] Yes
[X] No
```
=> Add logging for DefaultPanelCompositionMigration

src/main/java/uk/gov/hmcts/reform/migration/service/CaseMigrationProcessor.java
reduce number of cases processed at same time
```
[ ] Yes
[X] No
```
=> Reduce parallelism to 10

src/main/java/uk/gov/hmcts/reform/migration/service/migrate/DefaultPanelCompositionMigration.java
- https://tools.hmcts.net/jira/browse/SSCSCI-2005
- fix log message
```
[ ] Yes
[x] No
```
=> SSCSCI-2005: fix log msg

build.gradle
- https://tools.hmcts.net/jira/browse/SSCSCI-1993
- bump up sscs-common to v6.3.10
- add equals method to PanelMemberComposition to ensure consistent equality check during ULR
```
[ ] Yes
[x] No
```
=> bump up sscs-common to v6.3.10

build.gradle
Fix incompatibility between spring boot and spring cloud
```
[ ] Yes
[ ] No
```
=> upgrade spring cloud
